groups:
  - owner
  - developer
  - staffmanager
  - forumsmanager
  - supportmanager
  - communitymanager
  - advisor
  - sradmin
  - admin
  - srmod
  - mod
  - helper

#server MUST to exist in bungeecord's config.yml or plugin WILL crash
servers:
  - opfactions
